# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 21
  dof_obs_size: 20
  actions_dim: 20
  lower_body_actions_dim: 12 
  upper_body_actions_dim: 8 
  policy_obs_dim: -1 
  critic_obs_dim: -1

  key_bodies: ["l_ankle_roll_link", "r_ankle_roll_link"]
  contact_bodies: [ "l_ankle_roll_link", "r_ankle_roll_link" ]
  num_feet: 2
  right_foot_name: "r_ankle_roll_link"
  left_foot_name: "l_ankle_roll_link"
  foot_name: "ankle_roll_link"
  knee_name: "calf_link"
  has_torso: True
  torso_name: "base_link"
  has_upper_body_dof: True
  
  dof_names: ['l_hip_pitch_joint', 'l_hip_roll_joint', 'l_thigh_joint', 'l_calf_joint', 'l_ankle_pitch_joint', 'l_ankle_roll_joint',
              'l_shoulder_pitch_joint', 'l_shoulder_roll_joint', 'l_upper_arm_joint', 'l_elbow_joint',

              'r_hip_pitch_joint', 'r_hip_roll_joint', 'r_thigh_joint', 'r_calf_joint', 'r_ankle_pitch_joint', 'r_ankle_roll_joint',
              'r_shoulder_pitch_joint', 'r_shoulder_roll_joint', 'r_upper_arm_joint', 'r_elbow_joint']
              
  upper_dof_names: ['l_shoulder_pitch_joint', 'l_shoulder_roll_joint', 'l_upper_arm_joint', 'l_elbow_joint',
                    'r_shoulder_pitch_joint', 'r_shoulder_roll_joint', 'r_upper_arm_joint', 'r_elbow_joint']
                    
  upper_left_arm_dof_names: ['l_shoulder_pitch_joint', 'l_shoulder_roll_joint', 'l_upper_arm_joint', 'l_elbow_joint']
  upper_right_arm_dof_names: ['r_shoulder_pitch_joint', 'r_shoulder_roll_joint', 'r_upper_arm_joint', 'r_elbow_joint']
  
  lower_dof_names: ['l_hip_pitch_joint', 'l_hip_roll_joint', 'l_thigh_joint', 'l_calf_joint', 'l_ankle_pitch_joint', 'l_ankle_roll_joint',
                    'r_hip_pitch_joint', 'r_hip_roll_joint', 'r_thigh_joint', 'r_calf_joint', 'r_ankle_pitch_joint', 'r_ankle_roll_joint']

  # Joint limits based on URDF
  dof_pos_lower_limit_list: [-2.5307, -0.29, -2.7576, 0.017267, -0.87267, -0.2618, 
                             -3.0892, -0.36, -1.65 , -1.9, 
                             -2.5307, -2.9671, -2.7576, 0.017267, -0.87267, -0.2618, 
                             -3.0892, -2.2882, -1.65 , -1.9]
  dof_pos_upper_limit_list: [2.8798, 2.9671, 2.7576, 2.48, 0.5236, 0.2618, 
                             1.01, 2.2882, 1.65 , 0.0036,
                             2.8798, 0.29, 2.7576, 2.48, 0.5236, 0.2618, 
                             1.01, 0.36, 1.65 , 0.0036]
                             
  dof_vel_limit_list: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0,  # left leg
                       10.0, 10.0, 10.0, 10.0, 10.0, 10.0,  # right leg
                       10.0, 10.0, 10.0, 10.0,  # left arm
                       10.0, 10.0, 10.0, 10.0]  # right arm
                       
  dof_effort_limit_list: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0,  # left leg
                          20.0, 20.0, 20.0, 20.0, 20.0, 20.0,  # right leg
                          20.0, 20.0, 20.0, 20.0,  # left arm
                          20.0, 20.0, 20.0, 20.0]  # right arm

  # only apply for isaacsim
  dof_armature_list: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03, 0.03]
  # only apply for isaacsim
  dof_joint_friction_list: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03, 
                            0.03, 0.03, 0.03, 0.03]

  body_names: [
                'base_link',
                'l_hip_pitch_link', 'l_hip_roll_link', 'l_thigh_link', 'l_calf_link', 'l_ankle_pitch_link', 'l_ankle_roll_link',
                'l_shoulder_pitch_link', 'l_shoulder_roll_link', 'l_upper_arm_link', 'l_elbow_link', 
                
                'r_hip_pitch_link', 'r_hip_roll_link', 'r_thigh_link', 'r_calf_link', 'r_ankle_pitch_link', 'r_ankle_roll_link',
                'r_shoulder_pitch_link', 'r_shoulder_roll_link', 'r_upper_arm_link', 'r_elbow_link', 
                ]

  terminate_after_contacts_on : []
  penalize_contacts_on: ["shoulder", "hip", "elbow", "arm",'calf']
  
  init_state:
    pos: [0.0, 0.0, 0.35] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat] 
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      l_hip_pitch_joint: 0.0
      l_hip_roll_joint: 0.0
      l_thigh_joint: 0.0
      l_calf_joint: 0.0
      l_ankle_pitch_joint: 0.0
      l_ankle_roll_joint: 0.0
      r_hip_pitch_joint: 0.0
      r_hip_roll_joint: 0.0
      r_thigh_joint: 0.0
      r_calf_joint: 0.0
      r_ankle_pitch_joint: 0.0
      r_ankle_roll_joint: 0.0
      l_shoulder_pitch_joint: 0.0
      l_shoulder_roll_joint: 0.0
      l_upper_arm_joint: 0.0
      l_elbow_joint: 0.0
      r_shoulder_pitch_joint: 0.0
      r_shoulder_roll_joint: 0.0
      r_upper_arm_joint: 0.0
      r_elbow_joint: 0.0

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_pitch: 80
      hip_roll: 80
      thigh: 80
      calf: 80
      ankle_pitch: 80
      ankle_roll: 80
      shoulder_pitch: 30
      shoulder_roll: 30
      upper_arm: 15
      elbow: 30

    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_pitch: 1.1
      hip_roll: 1.1
      thigh: 1.1
      calf: 1.1
      ankle_pitch: 1.1
      ankle_roll: 1.1
      shoulder_pitch: 0.6
      shoulder_roll: 0.6
      upper_arm: 0.6
      elbow: 0.6

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.02 # 0.001 # isaacgym armature is set by this
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    # urdf_file: "pi+/urdf/pi+_22dof.urdf"
    urdf_file: "pi+_all/pi_plus_20dof_250828/urdf/pi_plus_20dof_250828.urdf"


    usd_file: "pi+_all/pi_plus_20dof_250828/pi+pi_20dof.usd"
    # xml_file: "pi+/xml/pi_box_l_g.xml"
    xml_file: "pi+_all/pi_plus_20dof_250828/xml/pi_20dof_0828.xml"
    robot_type: pi_20dof
    self_collisions: 0
    default_dof_drive_mode: 3

    fix_base_link: False

  motion:
    motion_lib_type: 'WJX'
    motion_file : ???
    asset:
      assetRoot: "description/robots/pi+_all/pi_plus_20dof_250828/xml/" 
      # assetFileName: "pi_box_l_g.xml"
      assetFileName: "pi_20dof_0828.xml"

    humanoid_type: pi_20dof_nowaist
    bias_offset: False
    has_self_collision: True
    has_mesh: False
    has_jt_limit: False
    has_dof_subset: True
    has_upright_start: True
    has_smpl_pd_offset: False
    remove_toe: False
    motion_sym_loss: False
    sym_loss_coef: 1
    big_ankle: True

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: False

    masterfoot: False
    freeze_toe: false
    freeze_hand: False
    box_body: True
    real_weight: True
    real_weight_porpotion_capsules: True
    real_weight_porpotion_boxes: True

    body_names: [ 'base_link',
                 'l_hip_pitch_link', 'l_hip_roll_link', 'l_thigh_link', 'l_calf_link', 'l_ankle_pitch_link', 'l_ankle_roll_link', 
                 'l_shoulder_pitch_link', 'l_shoulder_roll_link', 'l_upper_arm_link', 'l_elbow_link', 
                 'r_hip_pitch_link', 'r_hip_roll_link', 'r_thigh_link', 'r_calf_link', 'r_ankle_pitch_link', 'r_ankle_roll_link', 
                 'r_shoulder_pitch_link', 'r_shoulder_roll_link', 'r_upper_arm_link', 'r_elbow_link', 


                 ]
          
    limb_weight_group: 
      - ['base_link']
      - ['l_hip_pitch_link', 'l_hip_roll_link', 'l_thigh_link', 'l_calf_link', 'l_ankle_pitch_link', 'l_ankle_roll_link']
      - ['l_shoulder_pitch_link', 'l_shoulder_roll_link', 'l_upper_arm_link', 'l_elbow_link']
      - ['r_hip_pitch_link', 'r_hip_roll_link', 'r_thigh_link', 'r_calf_link', 'r_ankle_pitch_link', 'r_ankle_roll_link']
      - ['r_shoulder_pitch_link', 'r_shoulder_roll_link', 'r_upper_arm_link', 'r_elbow_link']

    dof_names: ['l_hip_pitch_link', 'l_hip_roll_link', 'l_thigh_link', 'l_calf_link', 'l_ankle_pitch_link', 'l_ankle_roll_link', 
                'l_shoulder_pitch_link', 'l_shoulder_roll_link', 'l_upper_arm_link', 'l_elbow_link', 
                'r_hip_pitch_link', 'r_hip_roll_link', 'r_thigh_link', 'r_calf_link', 'r_ankle_pitch_link', 'r_ankle_roll_link', 
                'r_shoulder_pitch_link', 'r_shoulder_roll_link', 'r_upper_arm_link', 'r_elbow_link']
                
    right_foot_name: 'r_ankle_roll_link'
    left_foot_name: 'l_ankle_roll_link'

    nums_extend_bodies: 1
    extend_config:
      - joint_name: "l_wrist_link"
        parent_name: "l_elbow_link"
        pos: [ 0, 0.0, -0.0724]
        rot: [ 1.0, 0.0, 0.0, 0.0 ] # w x y z
      - joint_name: "r_wrist_link"
        parent_name: "r_elbow_link"
        pos: [ -0.0, 0.0, -0.0724 ]
        rot: [ 1.0, 0.0, 0.0, 0.0 ] # w x y z
      - joint_name: "head_link"
        parent_name: "base_link"
        pos: [0.0, 0.0, 0.24]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z

    motion_tracking_link:
      - "l_wrist_link"
      - "r_wrist_link"
      - "head_link"

    lower_body_link:
      - "l_hip_pitch_link"
      - "l_hip_roll_link"
      - "l_thigh_link"
      - "l_calf_link"
      - "l_ankle_pitch_link"
      - "l_ankle_roll_link"
      - "r_hip_pitch_link"
      - "r_hip_roll_link"
      - "r_thigh_link"
      - "r_calf_link"
      - "r_ankle_pitch_link"
      - "r_ankle_roll_link"
      - "base_link"

    upper_body_link:
      - "l_shoulder_pitch_link"
      - "l_shoulder_roll_link"
      - "l_upper_arm_link"
      - "l_elbow_link"
      - "l_wrist_link"
      - "r_shoulder_pitch_link"
      - "r_shoulder_roll_link"
      - "r_upper_arm_link"
      - "r_elbow_link"
      - "r_wrist_link"
      - "head_link"

    pelvis_link: "base_link"
    base_link: "base_link"
    hips_link:
      - "l_hip_pitch_link"
      - "l_hip_roll_link"
      - "l_thigh_link"
      - "r_hip_pitch_link"
      - "r_hip_roll_link"
      - "r_thigh_link"
    
    joint_matches:
      - ["base_link", "Pelvis"]
      - ["l_hip_pitch_link", "L_Hip"]
      - ["l_calf_link", "L_Knee"]
      - ["l_ankle_pitch_link", "L_Ankle"]
      - ["r_hip_pitch_link", "R_Hip"]
      - ["r_calf_link", "R_Knee"]
      - ["r_ankle_pitch_link", "R_Ankle"]
      - ["l_shoulder_roll_link", "L_Shoulder"]
      - ["l_elbow_link", "L_Elbow"]
      - ["l_wrist_link", "L_Hand"]
      - ["r_shoulder_roll_link", "R_Shoulder"]
      - ["r_elbow_link", "R_Elbow"]
      - ["r_wrist_link", "R_Hand"]
      - ["head_link", "Head"]

    smpl_pose_modifier:
      - Pelvis: "[np.pi/2, 0, np.pi/2]"
      - L_Shoulder: "[0, 0, -np.pi/2]"
      - R_Shoulder: "[0, 0, np.pi/2]"

    

    visualization:
      customize_color : True
      marker_joint_colors : 
      - [0.929, 0.867, 0.437] # waist_link
      - [0.929, 0.867, 0.437] # l_hip_pitch_joint
      - [0.929, 0.867, 0.437] # l_hip_roll_joint
      - [0.929, 0.867, 0.437] # l_thigh_joint
      - [0.929, 0.867, 0.437] # l_calf_joint
      - [0.929, 0.867, 0.437] # l_ankle_pitch_joint
      - [0.929, 0.867, 0.437] # l_ankle_roll_joint
      - [0.929, 0.867, 0.437] # r_hip_pitch_joint
      - [0.929, 0.867, 0.437] # r_hip_roll_joint
      - [0.929, 0.867, 0.437] # r_thigh_joint
      - [0.929, 0.867, 0.437] # r_calf_joint
      - [0.929, 0.867, 0.437] # r_ankle_pitch_joint
      - [0.929, 0.867, 0.437] # r_ankle_roll_joint
      - [0.929, 0.867, 0.437] # l_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # l_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # l_shoulder_upper_arm_joint
      - [0.929, 0.867, 0.437] # l_elbow_joint
      - [0.929, 0.867, 0.437] # l_wrist_joint
      - [0.929, 0.867, 0.437] # r_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # r_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # r_shoulder_upper_arm_joint
      - [0.929, 0.867, 0.437] # r_elbow_joint
      - [0.929, 0.867, 0.437] # r_wrist_joint
      - [0, 0.351, 0.613] # head_link 